<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.q1689pp' shared service.

return $this->services['service_locator.q1689pp'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('ourCustomService' => function () {
    $f = function (\AppBundle\Service\OurCustomService $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Service\OurCustomService']) ? $this->services['AppBundle\Service\OurCustomService'] : $this->load(__DIR__.'/getOurCustomServiceService.php')) && false ?: '_'});
}));
