<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fun_event_listener' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Event/Listener/FunEventListener.php';

return $this->services['fun_event_listener'] = new \AppBundle\Event\Listener\FunEventListener();
