<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'reddit_scraper' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Service/RedditScraper.php';

return $this->services['reddit_scraper'] = new \AppBundle\Service\RedditScraper(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
