<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Service\OurCustomService' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Service/OurCustomService.php';

return $this->services['AppBundle\Service\OurCustomService'] = new \AppBundle\Service\OurCustomService(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
