<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.middleware.log.8p_guzzle_client' shared service.

include_once $this->targetDirs[3].'/vendor/eightpoints/guzzle-bundle/src/Middleware/LogMiddleware.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/MessageFormatter.php';

return $this->services['eight_points_guzzle.middleware.log.8p_guzzle_client'] = new \EightPoints\Bundle\GuzzleBundle\Middleware\LogMiddleware(${($_ = isset($this->services['eight_points_guzzle.logger']) ? $this->services['eight_points_guzzle.logger'] : $this->services['eight_points_guzzle.logger'] = new \EightPoints\Bundle\GuzzleBundle\Log\Logger()) && false ?: '_'}, ${($_ = isset($this->services['eight_points_guzzle.formatter']) ? $this->services['eight_points_guzzle.formatter'] : $this->services['eight_points_guzzle.formatter'] = new \GuzzleHttp\MessageFormatter()) && false ?: '_'});
