<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.middleware.request_time.8p_guzzle_client' shared service.

include_once $this->targetDirs[3].'/vendor/eightpoints/guzzle-bundle/src/Middleware/RequestTimeMiddleware.php';

return $this->services['eight_points_guzzle.middleware.request_time.8p_guzzle_client'] = new \EightPoints\Bundle\GuzzleBundle\Middleware\RequestTimeMiddleware(${($_ = isset($this->services['eight_points_guzzle.data_collector']) ? $this->services['eight_points_guzzle.data_collector'] : $this->getEightPointsGuzzle_DataCollectorService()) && false ?: '_'});
