<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.client.8p_guzzle_client' shared service.

include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/HandlerStack.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/Client.php';

$a = \GuzzleHttp\HandlerStack::create();
$a->push(${($_ = isset($this->services['eight_points_guzzle.middleware.log.8p_guzzle_client']) ? $this->services['eight_points_guzzle.middleware.log.8p_guzzle_client'] : $this->load(__DIR__.'/getEightPointsGuzzle_Middleware_Log_8pGuzzleClientService.php')) && false ?: '_'}->log(), 'log');
$a->push(${($_ = isset($this->services['eight_points_guzzle.middleware.request_time.8p_guzzle_client']) ? $this->services['eight_points_guzzle.middleware.request_time.8p_guzzle_client'] : $this->load(__DIR__.'/getEightPointsGuzzle_Middleware_RequestTime_8pGuzzleClientService.php')) && false ?: '_'}, 'request_time');
$a->push(${($_ = isset($this->services['eight_points_guzzle.middleware.symfony_log']) ? $this->services['eight_points_guzzle.middleware.symfony_log'] : $this->load(__DIR__.'/getEightPointsGuzzle_Middleware_SymfonyLogService.php')) && false ?: '_'}, 'symfony_log');
$a->unshift(${($_ = isset($this->services['eight_points_guzzle.middleware.event_dispatch.8p_guzzle_client']) ? $this->services['eight_points_guzzle.middleware.event_dispatch.8p_guzzle_client'] : $this->load(__DIR__.'/getEightPointsGuzzle_Middleware_EventDispatch_8pGuzzleClientService.php')) && false ?: '_'}->dispatchEvent(), 'events');

return $this->services['eight_points_guzzle.client.8p_guzzle_client'] = new \GuzzleHttp\Client(array('base_uri' => '', 'handler' => $a));
