<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.middleware.event_dispatch.8p_guzzle_client' shared service.

include_once $this->targetDirs[3].'/vendor/eightpoints/guzzle-bundle/src/Middleware/EventDispatchMiddleware.php';

return $this->services['eight_points_guzzle.middleware.event_dispatch.8p_guzzle_client'] = new \EightPoints\Bundle\GuzzleBundle\Middleware\EventDispatchMiddleware(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, '8p_guzzle_client');
