<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Event\Subscriber\FunEventSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Event/Subscriber/FunEventSubscriber.php';

return $this->services['AppBundle\Event\Subscriber\FunEventSubscriber'] = new \AppBundle\Event\Subscriber\FunEventSubscriber();
