<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'github_api' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Service/HttpClientInterface.php';
include_once $this->targetDirs[3].'/src/AppBundle/Service/BuzzHttpClient.php';
include_once $this->targetDirs[3].'/src/AppBundle/Service/GitHubApi.php';

return $this->services['github_api'] = new \AppBundle\Service\GitHubApi(new \AppBundle\Service\BuzzHttpClient());
