<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCapdwed\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCapdwed/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCapdwed.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCapdwed\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCapdwed\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Capdwed',
    'container.build_id' => 'a9ef8400',
    'container.build_time' => 1522193665,
));
