<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFrqrmpu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFrqrmpu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFrqrmpu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFrqrmpu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFrqrmpu\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Frqrmpu',
    'container.build_id' => 'f914f2f7',
    'container.build_time' => 1522213354,
));
